// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caexqppoqzojzekqaauf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZXhxcHBvcXpvanpla3FhYXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTM5ODIsImV4cCI6MjA3MzkyOTk4Mn0.xpahVj_RmmZtPxRjT8SQucwtAci47HMrxtFOa7wr1ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});